parameters:
    admin.user.model.class: IHorse\BackendBundle\Model\Handler\AdminUserHandler
    rest.handler.class: IHorse\BackendBundle\Model\Handler\RESTHandler
    clinic.json.type: IHorse\BackendBundle\Form\Type\JsonClinicType
    owner.json.type: IHorse\BackendBundle\Form\Type\JsonOwnerType
    image.handler.class: IHorse\BackendBundle\Model\Handler\ImageHandler
    history.handler.class: IHorse\BackendBundle\Model\Handler\HistoryHandler
    horse.json.type: IHorse\BackendBundle\Form\Type\JsonHorseType
    expirable.action.listener.class: IHorse\BackendBundle\EventListener\ExpirableActionListener
    dental.handler.class: IHorse\BackendBundle\Model\Handler\DentalHandler

services:
    rest.handler.model:
        class: %rest.handler.class%
        arguments: [@ihorse.client]    
    image.handler.model:
        class: %image.handler.class%
        arguments: [@ihorse.client]
    history.handler.model:
        class: %history.handler.class%
        arguments: [@ihorse.client]
    dental.handler.model:
        class: %dental.handler.class%
        arguments: [@ihorse.client]

    form.type.json.clinic:
        class: %clinic.json.type%
        arguments:
            - @rest.handler.model
            - @service_container
        tags:
            - { name: form.type, alias: json_clinic }

    form.type.json.owner:
        class: %owner.json.type%
        arguments:
            - @rest.handler.model
            - @service_container
        tags:
            - { name: form.type, alias: json_owner }

    form.type.json.horse:
        class: %horse.json.type%
        arguments:
            - @rest.handler.model
            - @service_container
        tags:
            - { name: form.type, alias: json_horse }

    expirable.action_listener:
        class: %expirable.action.listener.class%
        arguments: [@service_container]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: onKernelController }