parameters:
    admin.user.model.class: IHorse\BackendBundle\Model\Handler\AdminUserHandler
    veterinary.handler.class: IHorse\BackendBundle\Model\Handler\VeterinaryHandler
    clinic.handler.class: IHorse\BackendBundle\Model\Handler\ClinicHandler
    owner.handler.class: IHorse\BackendBundle\Model\Handler\OwnerHandler
    clinic.json.type: IHorse\BackendBundle\Form\Type\JsonClinicType

services:
    user.model:
        class: %admin.user.model.class%
        arguments: [@ihorse.client]
    veterinary.handler.model:
        class: %veterinary.handler.class%
        arguments: [@ihorse.client]
    clinic.handler.model:
        class: %clinic.handler.class%
        arguments: [@ihorse.client]
    owner.handler.model:
        class: %owner.handler.class%
        arguments: [@ihorse.client]
    form.type.json.clinic:
        class: %clinic.json.type%
        arguments:
            - @clinic.handler.model
        tags:
            - { name: form.type, alias: json_clinic }