parameters:
    admin.user.model.class: IHorse\BackendBundle\Model\Handler\AdminUserHandler
    veterinary.handler.class: IHorse\BackendBundle\Model\Handler\VeterinaryHandler
    clinic.handler.class: IHorse\BackendBundle\Model\Handler\ClinicHandler
    owner.handler.class: IHorse\BackendBundle\Model\Handler\OwnerHandler
    clinic.json.type: IHorse\BackendBundle\Form\Type\JsonClinicType
    horse.handler.class: IHorse\BackendBundle\Model\Handler\HorseHandler
    owner.json.type: IHorse\BackendBundle\Form\Type\JsonOwnerType
    image.handler.class: IHorse\BackendBundle\Model\Handler\ImageHandler
    history.handler.class: IHorse\BackendBundle\Model\Handler\HistoryHandler
    horse.json.type: IHorse\BackendBundle\Form\Type\JsonHorseType

services:
    user.model:
        class: %admin.user.model.class%
        arguments: [@ihorse.client]
    veterinary.handler.model:
        class: %veterinary.handler.class%
        arguments: [@ihorse.client]
    clinic.handler.model:
        class: %clinic.handler.class%
        arguments: [@ihorse.client]
    owner.handler.model:
        class: %owner.handler.class%
        arguments: [@ihorse.client]
    horse.handler.model:
        class: %horse.handler.class%
        arguments: [@ihorse.client]
    image.handler.model:
        class: %image.handler.class%
        arguments: [@ihorse.client]
    history.handler.model:
        class: %history.handler.class%
        arguments: [@ihorse.client]

    form.type.json.clinic:
        class: %clinic.json.type%
        arguments:
            - @clinic.handler.model
        tags:
            - { name: form.type, alias: json_clinic }

    form.type.json.owner:
        class: %owner.json.type%
        arguments:
            - @owner.handler.model
        tags:
            - { name: form.type, alias: json_owner }

    form.type.json.horse:
        class: %horse.json.type%
        arguments:
            - @horse.handler.model
        tags:
            - { name: form.type, alias: json_horse }