imports:
    - { resource: config.yml }

parameters:
    ihorse.rest.uri: "http://www.rest.dentalhorse.com/"
    ihorse.rest.oauth.id: 1_4w26blqsue808ccso4so44kc44wgsowgwsgsogswc4goc0gwg0
    ihorse.rest.oauth.secret: 4yiofcgaueckw0ggowo4kock4kk8sk0kg0gs0wg4o4gc8co0s4

#framework:
#    validation:
#        cache: apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc

monolog:
    handlers:
        main:
            type:         fingers_crossed
            action_level: error
            handler:      nested
        nested:
            type:  stream
            path:  %kernel.logs_dir%/%kernel.environment%.log
            level: debug
