new_image:
    pattern: /new/{horseId}/{dentalId}
    defaults: { _controller: BackendBundle:Image:newImage }

create_image:
    pattern: /create/{horseId}/{dentalId}
    defaults: { _controller: BackendBundle:Image:createImage }

delete_image:
    pattern: /delete/{id}
    defaults: { _controller: BackendBundle:Image:deleteImage }